version: '3.4'

services:

  lista-telefonica-api:
    image: listatelefonicaapi
    build:
      context: .
      dockerfile: ListaTelefonica.API/Dockerfile
      
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - '5005:80'    
    networks:
      - local-network    

    healthcheck:
      test: 'curl -s http://localhost:5005/api/healthcheck >/dev/null; if [[ $$? == 52 ]]; then echo 0; else echo 1;'
      interval: 30s
      timeout: 10s
      retries: 5


networks:
  local-network:
    driver: bridge 